### PR TITLE
Major book refactoring and revision

### PR DESCRIPTION
**Pull request by TomasBeuzen**
This PR includes:
- General structural changes to book and repo  (closes: #28)
- Added a preface and introduction  (closes: #31, closes: #32)
- Move some chapters to appendices

### CODE REVIEW

**Comment by ttimbers** [comment]
When are you planning on merging this PR? I am going to heavily use this book for teaching after reading week and I need to get the links in order for the course a bit before then. Also, do you need my review on this?

**Comment by TomasBeuzen** [comment]
@ttimbers not planning on merging anytime soon, like 2-3 months, (also won't need reviews until then), I'm going to keep developing here and then branch off this PR too. So you can go ahead and refer to the book as it is for the upcoming course.

**Comment by ttimbers** [comment]
But will the students miss all your new good things then?

**Comment by TomasBeuzen** [comment]
Okay - change of plan. I'll finish refactoring and will merge this by the end of the week (this will push the new directory/site structure). Then I'll continue developing chapter-by-chapter with new PRs and will push when they're ready (these won't change the structure though so your links should be fine).

**Comment by TomasBeuzen** [comment]
@ttimbers - this is almost ready to go. This PR includes:
- General structural changes to book and repo
- Add a preface and introduction
- Move some chapters to appendices

At this point, I won't be changing the structure of the book/repo anymore, I'll just be updating or adding to it. But feel free to see the [netlify preview](https://deploy-preview-33--zen-ptolemy-4bba7d.netlify.app/) above. So any links you make should be good. You don't need to review any of the new material yet (preface, introduction, setup) as I would classify them as still WIP and will make separate PRs when I'm ready for them to be reviewed. I will note that I added our pictures and a short bio [here](https://deploy-preview-33--zen-ptolemy-4bba7d.netlify.app/00-preface#about-the-authors). LMK if you don't want your picture there - we can edit the bios when I make a separate PR for that section?

**Comment by TomasBeuzen** [comment]
@ttimbers - this is ready to merge. The only thing I'll note is that I significantly shortened the "[RStudio setup](https://deploy-preview-33--zen-ptolemy-4bba7d.netlify.app/02-setup#rstudio)" section. As this is going to be a text book I'd like it to stay relevant for as long as possible, so I'm trying to remove highly specific instructions like we had, and instead refer readers to the relevant documentation.

**Comment by ttimbers** [comment]
Sounds good to me! Thanks for pushing this refactoring, I am going to merge now as I am needing to get the links for the course today.

**Pull request merged**
